name: Build Image
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clippy:
    name: build iso
    runs-on: ubuntu-latest
    container: docker.io/library/archlinux:latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          pacman-key --init
          pacman-key --populate
          pacman -Syu --needed --noconfirm
          pacman -S git archiso --needed --noconfirm
          git clone https://github.com/blizOS/blizOS.git
          cd blizOS
          bash steps.sh
